export const cuboids = [
  {
    id: 'c_1',
    width: 350,
    height: 80,
    length: 350,
    color: '#726eff',
  },
  {
    id: 'c_2',
    width: 175,
    height: 80,
    length: 80,
    color: '#ffcc82',
  },
  {
    id: 'c_3',
    width: 80,
    height: 80,
    length: 175,
    color: '#d4e7ff',
  },
  {
    id: 'c_4',
    width: 80,
    height: 80,
    length: 80,
    color: '#d4e7ff',
  },
  {
    id: 'c_5',
    width: 80,
    height: 80,
    length: 80,
    color: '#d3d0ff',
  },
  {
    id: 'c_6',
    width: 80,
    height: 80,
    length: 80,
    color: '#d3d0ff',
    variants: { enter: { z: 30 }, exit: { z: 0 } },
  },
  {
    id: 'c_7',
    width: 80,
    height: 80,
    length: 80,
    color: '#d3d0ff',
    variants: { enter: { x: 30 }, exit: { x: 0 } },
  },
  {
    id: 'c_8',
    width: 80,
    height: 80,
    length: 80,
    color: '#ffe0f2',
    variants: { enter: { y: -90 }, exit: { y: 0 } },
  },
  {
    id: 'c_9',
    width: 50,
    height: 50,
    length: 50,
    color: '#ffe0f2',
    variants: { enter: { z: [100, 0] }, exit: { z: 100 } },
  },
  {
    id: 'c_10',
    width: 25,
    height: 25,
    length: 25,
    color: '#ebebeb',
  },
  {
    id: 'c_11',
    width: 25,
    height: 25,
    length: 25,
    color: '#ebebeb',
  },
]

export const spheres = [
  {
    id: 's_1',
    radius: 55,
    color: '#ff9c19',
    variants: { enter: { y: -115 }, exit: { y: 0 } },
  },
  {
    id: 's_2',
    radius: 40,
    color: '#ffffff',
  },
  {
    id: 's_3',
    radius: 35,
    color: '#ffffff',
    variants: { enter: { y: [50, 0] }, exit: { y: 50 } },
  },
]
