export const cuboids = [
  {
    id: 'c_1',
    width: 350,
    height: 80,
    length: 350,
    color: '#726eff',
  },
  {
    id: 'c_2',
    width: 175,
    height: 80,
    length: 80,
    color: '#ffcc82',
  },
  {
    id: 'c_3',
    width: 80,
    height: 80,
    length: 175,
    color: '#d4e7ff',
  },
  {
    id: 'c_4',
    width: 80,
    height: 80,
    length: 80,
    color: '#d4e7ff',
  },
  {
    id: 'c_5',
    width: 80,
    height: 80,
    length: 80,
    color: '#d3d0ff',
  },
  {
    id: 'c_6',
    width: 80,
    height: 80,
    length: 80,
    color: '#d3d0ff',
    animateInfo: { z: [0, 30] },
  },
  {
    id: 'c_7',
    width: 80,
    height: 80,
    length: 80,
    color: '#d3d0ff',
    animateInfo: { x: [0, -30] },
  },
  {
    id: 'c_8',
    width: 80,
    height: 80,
    length: 80,
    color: '#ffe0f2',
    animateInfo: { y: [0, -90] },
  },
  {
    id: 'c_9',
    width: 50,
    height: 50,
    length: 50,
    color: '#ffe0f2',
    animateInfo: { z: [100, 0] },
  },
  {
    id: 'c_10',
    width: 25,
    height: 25,
    length: 25,
    color: '#ebebeb',
  },
  {
    id: 'c_11',
    width: 25,
    height: 25,
    length: 25,
    color: '#ebebeb',
  },
]

export const spheres = [
  {
    id: 's_1',
    radius: 55,
    color: '#ff9c19',
    animateInfo: { y: [0, -115] },
  },
  {
    id: 's_2',
    radius: 40,
    color: '#ffffff',
  },
  {
    id: 's_3',
    radius: 35,
    color: '#ffffff',
    animateInfo: { y: [50, 0] },
  },
]
