export const cuboids = [
  {
    id: 1,
    width: 350,
    height: 80,
    length: 350,
    front: "#3537c8",
    left: "#494bfe",
    top: "#726eff",
  },
  {
    id: 2,
    width: 175,
    height: 80,
    length: 80,
    front: "#c47f20",
    left: "#ffa92d",
    top: "#ffcc82",
  },
  {
    id: 3,
    width: 80,
    height: 80,
    length: 175,
    front: "#7fa7e5",
    left: "#a0caff",
    top: "#d4e7ff",
  },
  {
    id: 4,
    width: 80,
    height: 80,
    length: 80,
    front: "#7b9bca",
    left: "#a0caff",
    top: "#d4e7ff",
  },
  {
    id: 5,
    width: 80,
    height: 80,
    length: 80,
    front: "#9390cc",
    left: "#c1bdff",
    top: "#cdcafd",
  },
  {
    id: 6,
    width: 80,
    height: 80,
    length: 80,
    front: "#9390cc",
    left: "#c1bdff",
    top: "#cdcafd",
    animateInfo: { z: [0, 50] },
  },
  {
    id: 7,
    width: 80,
    height: 80,
    length: 80,
    front: "#9390cc",
    left: "#c1bdff",
    top: "#cdcafd",
    animateInfo: { x: [0, -50] },
  },
  {
    id: 8,
    width: 80,
    height: 80,
    length: 80,
    front: "#e8a9c0",
    left: "#ffcdeb",
    top: "#ffe0f2",
    animateInfo: { y: [0, -50] },
  },
  {
    id: 9,
    width: 50,
    height: 50,
    length: 50,
    front: "#e8a9c0",
    left: "#ffcdeb",
    top: "#ffe0f2",
  },
  {
    id: 10,
    width: 25,
    height: 25,
    length: 25,
    front: "#c9c9c9",
    left: "#dbdbdb",
    top: "#ebebeb",
  },
  {
    id: 11,
    width: 25,
    height: 25,
    length: 25,
    front: "#c9c9c9",
    left: "#dbdbdb",
    top: "#ebebeb",
  },
  {
    id: 200,
    width: 0,
    height: 0,
    length: 0,
    front: "#",
    left: "#",
    top: "#",
  },
];
